Repository NVIDIA-Merlin/systems, pull requests merged in 2022-05, with the labels that each got.

#97 docs: Add ext-toc and revisions for the change
  README.md
  docs/README.md
  docs/source/_templates/versions.html
  docs/source/conf.py
  docs/source/index.rst
  docs/source/toc.yaml
  examples/Getting_Started/README.md
  examples/Getting_Started/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  examples/README.md
  examples/README.rst
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  requirements-dev.txt
Labels: documentation

#103 Add common release-drafter configuration
  .github/release-drafter.yml
Labels: documentation

#106 Add release-drafter with workflow dispatch
  .github/workflows/release-drafter.yml
Labels: documentation

#108 Request to add labels to PRs
  CONTRIBUTING.md
Labels: chore

#109 add unit tests script
  .github/workflows/cpu-ci.yml
  ci/test_unit.sh
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/triton/export.py
  merlin/systems/triton/model_config.proto
  merlin/systems/triton/model_config_pb2.py
  tests/unit/systems/test_ensemble.py
  tests/unit/systems/test_inference_ops.py
  tests/unit/systems/test_tensorflow_inf_op.py
Labels: bug
