Repository NVIDIA-Merlin/systems, pull requests merged in 2022-09, with the labels that each got.

#192 introduce cascading timeout for tritonserver launch
  merlin/systems/triton/utils.py
Labels: chore, ci

#193 Move requirements files to a `requirements` sub-directory
  MANIFEST.in
  docs/README.md
  requirements/base.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/gpu.txt
  requirements/test-cpu.txt
  requirements/test-gpu.txt
  requirements/test.txt
  setup.py
  tox.ini
Labels: clean up, chore, ci

#197 Add properties for input and output schemas to `Ensemble`
  merlin/systems/dag/ensemble.py
  tests/unit/systems/dag/ops/test_ops.py
  tests/unit/systems/dag/test_graph.py
  tests/unit/systems/ops/tf/test_ensemble.py
Labels: enhancement, clean up

#198 Fix versioneer to get accurate version numbers
  merlin/systems/_version.py
  setup.cfg
  tests/unit/test_version.py
Labels: ci

#199 run example tests in pr
  .github/workflows/cpu-ci.yml
  tests/unit/examples/test_serving_an_xgboost_model_with_merlin_systems.py
  tox.ini
Labels: chore

#201 Mark the version test so it can be skipped in other repos
  pytest.ini
  tests/unit/test_version.py
Labels: chore, ci

#194 add implicit example
  examples/Serving-An-Implicit-Model-With-Merlin-Systems.ipynb
  requirements/test-cpu.txt
  tests/unit/examples/test_serving_an_implicit_model_with_merlin_systems.py
Labels: documentation, examples

#176 Write an integration test for T4R Torchscript serving
  examples/Serving-An-Implicit-Model-With-Merlin-Systems.ipynb
  examples/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/ops/__init__.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/dag/ops/softmax_sampling.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/triton/__init__.py
  merlin/systems/triton/utils.py
  tests/integration/t4r/test_pytorch_backend.py
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
  tests/unit/systems/dag/ops/test_ops.py
  tests/unit/systems/ops/fil/test_ensemble.py
  tests/unit/systems/ops/tf/test_ensemble.py
  tests/unit/systems/ops/torch/test_op.py
  tests/unit/systems/test_export.py
  tests/unit/systems/utils/triton.py
Labels: enhancement

#206 fix pinned feast versions
  requirements/gpu.txt
Labels: bug
