Repository NVIDIA-Merlin/systems, pull requests merged in 2022-08, with the labels that each got.

#152 Clean up model input signature handling for tuples
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/tensorflow.py
  tests/unit/systems/test_tensorflow_inf_op.py
Labels: bug

#146 Allow merlin.models.xgb.XGBoost in PredictForest
  merlin/systems/dag/ops/fil.py
  tests/unit/systems/fil/test_forest.py
Labels: enhancement

#158 Pass model kwargs through to operator from_config methods
  merlin/systems/dag/op_runner.py
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/feast.py
  merlin/systems/dag/ops/fil.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/session_filter.py
  merlin/systems/dag/ops/softmax_sampling.py
  merlin/systems/dag/ops/unroll_features.py
  merlin/systems/triton/oprunner_model.py
  tests/unit/systems/test_op_runner.py
  tests/unit/systems/utils/ops.py
Labels: enhancement

#155 Allow selection of multiple outputs with SampleSoftmax
  merlin/systems/dag/ops/softmax_sampling.py
  tests/unit/systems/dag/ops/test_softmax_sampling.py
  tests/unit/systems/test_ensemble_ops.py
Labels: bug, enhancement

#160 Add unit tests for QueryFeast op
  .github/workflows/cpu-ci.yml
  tests/unit/systems/dag/ops/test_feast.py
Labels: chore

#157 add xgboost serving example
  docs/source/toc.yaml
  examples/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
  tests/unit/examples/test_serving_an_xgboost_model_with_merlin_systems.py
Labels: examples

#161 use tox for github CI steps
  .github/workflows/cpu-ci.yml
  .github/workflows/fil.yml
  requirements-dev.txt
  requirements-docs.txt
  requirements-test-cpu.txt
  requirements-test-gpu.txt
  requirements-test.txt
  tox.ini
Labels: chore, ci

#162 Mark Feast tests with `pytest.importorskip`
  tests/unit/systems/dag/ops/test_feast.py
Labels: chore, ci

#163 Fix `importorskip` in Feast tests
  tests/unit/systems/dag/ops/test_feast.py
Labels: chore, ci

#165 Update `versioneer` from 0.21 to 0.23
  merlin/systems/__init__.py
  merlin/systems/_version.py
  versioneer.py
Labels: chore

#166 install more libraries in test environment
  requirements-test-cpu.txt
  tox.ini
Labels: chore, ci

#134 Add Operator for Implicit Models
  ci/ignore_codespell_words.txt
  merlin/systems/dag/ops/implicit.py
  merlin/systems/triton/oprunner_model.py
  requirements-test.txt
  tests/unit/systems/implicit/__init__.py
  tests/unit/systems/implicit/test_implicit.py
Labels: enhancement

#167 Add preliminary support for serving PyTorch models with TorchScript
  .pre-commit-config.yaml
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/triton/export.py
  merlin/systems/triton/models/oprunner_model.py
  merlin/systems/triton/models/pytorch_model.py
  merlin/systems/triton/models/workflow_model.py
  tests/unit/systems/tf/test_tf_op.py
  tests/unit/systems/torch/__init__.py
  tests/unit/systems/torch/test_torch.py
Labels: enhancement

#171 Revert "Allow selection of multiple outputs with SampleSoftmax"
  merlin/systems/dag/ops/softmax_sampling.py
  tests/unit/systems/dag/ops/test_softmax_sampling.py
  tests/unit/systems/test_ensemble_ops.py
Labels: bug

#172 revert change that renamed output schema
  merlin/systems/dag/ops/softmax_sampling.py
  tests/unit/systems/dag/ops/test_softmax_sampling.py
Labels: bug

#141 Enable gRPC port to be specified in `run_triton_server` and check if already running
  merlin/systems/triton/utils.py
  tests/unit/examples/test_serving_an_xgboost_model_with_merlin_systems.py
Labels: chore

#170 Organize the `tests` directory more clearly
  tests/unit/systems/dag/ops/test_ops.py
  tests/unit/systems/dag/test_graph.py
  tests/unit/systems/dag/test_model_registry.py
  tests/unit/systems/dag/test_op_runner.py
  tests/unit/systems/ops/__init__.py
  tests/unit/systems/ops/feast/__init__.py
  tests/unit/systems/ops/feast/test_op.py
  tests/unit/systems/ops/fil/__init__.py
  tests/unit/systems/ops/fil/test_ensemble.py
  tests/unit/systems/ops/fil/test_forest.py
  tests/unit/systems/ops/fil/test_op.py
  tests/unit/systems/ops/implicit/__init__.py
  tests/unit/systems/ops/implicit/test_op.py
  tests/unit/systems/ops/nvtabular/__init__.py
  tests/unit/systems/ops/nvtabular/test_op.py
  tests/unit/systems/ops/tf/__init__.py
  tests/unit/systems/ops/tf/test_ensemble.py
  tests/unit/systems/ops/tf/test_op.py
  tests/unit/systems/ops/torch/__init__.py
  tests/unit/systems/ops/torch/test_op.py
  tests/unit/systems/test_model_registry.py
Labels: clean up, chore

#175 Fix the `importorskip` for Torch tests
  tests/unit/systems/ops/torch/test_op.py
Labels: bug, ci

#178 feast should return np.float32 not np.float by default
  merlin/systems/dag/ops/feast.py
Labels: bug

#179 add test for QueryFeast.from_feature_view
  merlin/systems/dag/ops/feast.py
  tests/unit/systems/ops/feast/test_op.py
Labels: chore

#182 Required changes to get Rank example test passing
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
Labels: breaking, chore, ci

#183 add testenv to run merlin tests
  requirements-gpu.txt
  tox.ini
Labels: ci

#184 Specify `is_ragged=False` explicitly in the Feast tests
  tests/unit/systems/ops/feast/test_op.py
Labels: bug

#187 Add `tritonclient` as a test dependency
  requirements-test.txt
Labels: chore, ci

#190 Remove `importorskip("tritonclient")` from the tests
  tests/conftest.py
  tests/unit/systems/dag/test_model_registry.py
  tests/unit/systems/ops/fil/test_ensemble.py
  tests/unit/systems/ops/fil/test_forest.py
  tests/unit/systems/ops/fil/test_op.py
  tests/unit/systems/ops/implicit/test_op.py
  tests/unit/systems/ops/nvtabular/test_op.py
  tests/unit/systems/ops/tf/test_ensemble.py
  tests/unit/systems/ops/tf/test_op.py
  tests/unit/systems/ops/torch/test_op.py
  tests/unit/systems/test_export.py
  tests/unit/systems/utils/triton.py
Labels: chore, ci

#189 Add extra requirements files to `setup.py` as optional installs
  MANIFEST.in
  requirements-test.txt
  setup.py
Labels: chore, ci

#191 Skip "serving ranking models" example test on CPU
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
Labels: chore, ci

#185 Mark example notebook tests to make them skippable in other repos
  ci/test_unit.sh
  pytest.ini
  tests/unit/examples/test_serving_an_xgboost_model_with_merlin_systems.py
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
Labels: clean up, chore
