Repository NVIDIA-Merlin/systems, pull requests merged in 2022-03, with the labels that each got.

#42 Move interrogate docstring coverage settings to pyproject.toml
  .github/workflows/cpu-ci.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: documentation

#44 Remove unused dtype matching methods from `InferenceNode`
  merlin/systems/dag/node.py
Labels: clean up

#47 Exclude additional directories from docstring coverage checks
  pyproject.toml
Labels: documentation

#51 Copy Github issue templates from Merlin Models
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/submit-question.md
  .github/ISSUE_TEMPLATE/task.md
Labels: clean up

#50 Add a README
  README.md
Labels: documentation

#52 Docs add
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/node.py
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/feast.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/session_filter.py
  merlin/systems/dag/ops/softmax_sampling.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/ops/unroll_features.py
  merlin/systems/dag/ops/workflow.py
  requirements-dev.txt
Labels: documentation

#48 Merlin Systems example notebook
  .github/workflows/cpu-ci.yml
  examples/Getting_Started/Getting-started-with-Merlin-Systems.ipynb
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/feast.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/ops/workflow.py
Labels: documentation

#63 Fix `QueryFaiss.export` return type annotation
  merlin/systems/dag/ops/faiss.py
Labels: bug

#61 add torch to cpu ci
  .github/workflows/cpu-ci.yml
Labels: enhancement

#64 Fixes notebook bug bash edition
  examples/Getting_Started/Getting-started-with-Merlin-Systems.ipynb
Labels: bug

#65 Bump docstring coverage check threshold to 70%
  pyproject.toml
Labels: documentation

#67 fix links in nb
  examples/Getting_Started/Getting-started-with-Merlin-Systems.ipynb
Labels: documentation
