Repository NVIDIA-Merlin/systems, pull requests merged in 2022-12, with the labels that each got.

#237 update triton to allocate more cuda memory to pool size
  merlin/systems/triton/utils.py
Labels: enhancement

#241 refactor for torch operator to triton specific
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/runtime.py
  tests/unit/systems/dag/runtimes/triton/ops/torch/__init__.py
  tests/unit/systems/dag/runtimes/triton/ops/torch/test_op.py
Labels: enhancement, feature

#238 Nvt op runtime triton
  merlin/systems/dag/ops/workflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/__init__.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_ensemble.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_op.py
  tests/unit/systems/ops/fil/test_forest.py
Labels: enhancement, feature

#244 add import or skip for torch tests
  tests/unit/systems/dag/runtimes/triton/ops/torch/__init__.py
Labels: clean up, ci

#246 working local pytorch transform
  merlin/systems/dag/ops/pytorch.py
  tests/unit/systems/dag/runtimes/local/__init__.py
  tests/unit/systems/dag/runtimes/local/ops/__init__.py
  tests/unit/systems/dag/runtimes/local/ops/torch/__init__.py
  tests/unit/systems/dag/runtimes/local/ops/torch/test_op.py
  tests/unit/systems/dag/runtimes/local_runtime/__init__.py
  tests/unit/systems/dag/runtimes/local_runtime/ops/__init__.py
  tests/unit/systems/dag/runtimes/local_runtime/ops/torch/__init__.py
Labels: enhancement, feature

#242 Update API and add notebook
  docs/source/api.rst
  docs/source/toc.yaml
Labels: documentation

#247 Dictarray to and from df
  merlin/systems/dag/dictarray.py
Labels: enhancement, feature

#250 Address virtual dev review feedback
  examples/README.md
  requirements/test.txt
Labels: documentation

#251 detect when column is list of one argument per record
  merlin/systems/dag/dictarray.py
  tests/unit/systems/dag/test_column.py
Labels: clean up, feature

#245 working local runtime fil ops
  merlin/systems/dag/ops/fil.py
  tests/unit/systems/dag/runtimes/local/ops/fil/__init__.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_lightgbm.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_sklearn.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_xgboost.py
Labels: enhancement, feature

#236 Remove use of `hf_format` and `training` params for PyTorch inference test
  tests/integration/t4r/test_pytorch_backend.py
Labels: chore

#254 Use pre-commit for linting in GitHub Actions Workflow
  .github/workflows/cpu-ci.yml
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  .pylintrc
  merlin/systems/dag/ops/fil.py
  merlin/systems/dag/runtimes/triton/ops/operator.py
  merlin/systems/workflow/hugectr.py
  requirements/dev.txt
  tox.ini
  versioneer.py
Labels: ci

#255 changing the default runtime from Ensemble to Executor
  examples/Serving-An-Implicit-Model-With-Merlin-Systems.ipynb
  examples/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/runtimes/triton/__init__.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/triton/utils.py
  tests/integration/t4r/test_pytorch_backend.py
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
  tests/unit/systems/dag/ops/test_ops.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_lightgbm_triton.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_sklearn_triton.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_xgboost_triton.py
  tests/unit/systems/dag/runtimes/triton/ops/torch/test_op.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_ensemble.py
  tests/unit/systems/dag/runtimes/triton/test_triton.py
  tests/unit/systems/ops/fil/test_forest.py
  tests/unit/systems/ops/implicit/test_executor.py
  tests/unit/systems/ops/tf/test_ensemble.py
Labels: clean up, chore

#249 Nvt local runtime
  merlin/systems/dag/dictarray.py
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/dag/ops/workflow.py
  merlin/systems/triton/conversions.py
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
  tests/unit/systems/dag/runtimes/local/ops/nvtabular/__init__.py
  tests/unit/systems/dag/runtimes/local/ops/nvtabular/test_ensemble.py
  tests/unit/systems/dag/runtimes/triton/test_triton.py
  tests/unit/systems/dag/test_dict_array.py
  tests/unit/systems/ops/faiss/test_executor.py
  tox.ini
Labels: enhancement, feature

#256 Fix the Triton dtype of exported NVTabular workflow row length fields
  merlin/systems/triton/export.py
Labels: bug

#259 Move examples to integration
  tests/integration/examples/test_serving_an_implicit_model_with_merlin_systems.py
  tests/integration/examples/test_serving_an_xgboost_model_with_merlin_systems.py
  tests/integration/examples/test_serving_ranking_models_with_merlin_systems.py
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
Labels: clean up, chore, ci

#248 Tf local runtime
  merlin/systems/dag/dictarray.py
  merlin/systems/dag/ops/tensorflow.py
  tests/unit/systems/dag/runtimes/local/ops/tensorflow/__init__.py
  tests/unit/systems/dag/runtimes/local/ops/tensorflow/test_ensemble.py
Labels: enhancement, feature

#262 add gpu ci github actions workflow
  .github/workflows/gpu-ci.yml
Labels: clean up, chore, ci

#263 Replace merlin.models.loader.tf_utils with merlin.dataloader.tf_utils
  tests/integration/examples/test_serving_ranking_models_with_merlin_systems.py
  tests/unit/systems/ops/faiss/test_executor.py
Labels: chore

#264 adding async tf strategy for gpu memory
  ci/test_unit.sh
Labels: ci
