Repository NVIDIA-Merlin/systems, pull requests merged in 2022-07, with the labels that each got.

#130 Systems pb update
  merlin/systems/triton/oprunner_model.py
  merlin/systems/triton/workflow_model.py
Labels: bug, ci

#140 fix notebook and add unittest
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  requirements-dev.txt
  tests/conftest.py
  tests/unit/examples/test_serving_ranking_models_with_merlin_systems.py
Labels: bug

#147 Remove unnecessary docs dependencies
  docs/source/conf.py
  requirements-dev.txt
Labels: chore

#149 Load models from a model registry rather than path
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/model_registry.py
  tests/unit/systems/test_inference_ops.py
  tests/unit/systems/test_model_registry.py
Labels: enhancement

#150 Update precommit hook package versions
  .pre-commit-config.yaml
Labels: chore

#154 SoftmaxSampling should produce the same output dtype as the input
  merlin/systems/dag/ops/softmax_sampling.py
  tests/unit/systems/dag/ops/__init__.py
  tests/unit/systems/dag/ops/test_softmax_sampling.py
Labels: bug
