Repository NVIDIA-Merlin/systems, pull requests merged in 2022-10, with the labels that each got.

#95 Start using the `validate_schemas` hook from `core`
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/session_filter.py
Labels: clean up, chore

#212 Create a separate directory parallel to `unit` for version tests
  tests/version/test_version.py
Labels: chore

#213 Add `requests` dependency to base requirements
  requirements/base.txt
Labels: chore

#214 Update example notebook tests to write to temp directory.
  examples/Serving-An-Implicit-Model-With-Merlin-Systems.ipynb
  examples/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
  tests/unit/examples/test_serving_an_implicit_model_with_merlin_systems.py
  tests/unit/examples/test_serving_an_xgboost_model_with_merlin_systems.py
Labels: chore, ci

#215 tensorflow import or skip required for tf_utils
  tests/unit/systems/ops/faiss/test_executor.py
Labels: ci

#216 fix for faiss artifact path from config
  merlin/systems/dag/ops/faiss.py
Labels: bug

#217 Move Triton ensemble and executor export to runtime classes
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/runtimes/__init__.py
  merlin/systems/dag/runtimes/triton.py
  merlin/systems/triton/models/executor_model.py
  tests/unit/systems/dag/runtimes/__init__.py
  tests/unit/systems/dag/runtimes/test_triton.py
  tests/unit/systems/dag/test_executors.py
  tests/unit/systems/ops/faiss/test_executor.py
  tests/unit/systems/ops/fil/test_ensemble.py
  tests/unit/systems/ops/implicit/test_executor.py
  tests/unit/systems/ops/implicit/test_op.py
  tests/unit/systems/ops/tf/test_ensemble.py
Labels: clean up, chore

#218 Add `transform` method to `Ensemble`
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/runtimes/__init__.py
  merlin/systems/dag/runtimes/base_runtime.py
  merlin/systems/dag/runtimes/triton.py
  merlin/systems/triton/models/executor_model.py
Labels: clean up, chore
