Repository NVIDIA-Merlin/systems, pull requests merged in 2022-11, with the labels that each got.

#221 add env variable to handle gpu memory allocation
  tox.ini
Labels: bug, chore, ci

#219 Refactor TensorFlow operator into base and Triton runtime operator
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/runtimes/base_runtime.py
  merlin/systems/dag/runtimes/triton/__init__.py
  merlin/systems/dag/runtimes/triton/ops/__init__.py
  merlin/systems/dag/runtimes/triton/ops/operator.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/triton/export.py
  merlin/systems/triton/models/__init__.py
  merlin/systems/triton/models/executor_model.py
  merlin/systems/triton/models/oprunner_model.py
  tests/unit/systems/ops/tf/test_op.py
Labels: chore

#220 Update Pytorch integration test based on schema changes in T4R
  merlin/systems/dag/ops/__init__.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/triton/__init__.py
  tests/integration/t4r/test_pytorch_backend.py
Labels: enhancement

#223 Introduce and apply a basic version of the `Column` abstraction
  merlin/systems/dag/__init__.py
  merlin/systems/dag/dictarray.py
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/fil.py
  merlin/systems/dag/ops/implicit.py
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/dag/ops/softmax_sampling.py
  merlin/systems/dag/ops/workflow.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/triton/conversions.py
  merlin/systems/triton/models/executor_model.py
  merlin/systems/triton/models/oprunner_model.py
  tests/unit/systems/dag/runtimes/test_triton.py
  tests/unit/systems/dag/test_ensemble.py
  tests/unit/systems/dag/test_executors.py
  tests/unit/systems/dag/test_op_runner.py
  tests/unit/systems/ops/faiss/test_executor.py
  tests/unit/systems/utils/ops.py
Labels: clean up, chore

#224 Add multi-array `Columns` to `DictArray`
  merlin/systems/dag/dictarray.py
  merlin/systems/dag/ops/feast.py
  merlin/systems/triton/conversions.py
  tests/unit/systems/ops/feast/test_op.py
Labels: clean up, chore

#228 Update random sampling in tests to impove test reliability
  tests/unit/systems/dag/ops/test_ops.py
  tests/unit/systems/dag/test_ensemble.py
  tests/unit/systems/dag/test_executors.py
Labels: ci

#231 chore: Reduce docs size and update action versions
  .github/workflows/cpu-ci.yml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-remove-stale-reviews.yaml
  .github/workflows/docs-sched-rebuild.yaml
  docs/source/conf.py
Labels: chore, skip-changelog

#222 docs: Add basic SEO configuration
  docs/source/conf.py
Labels: documentation

#230 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: chore, ci, gpuCI-test-this

#232 fix container name and the link in the examples README
  examples/README.md
Labels: chore

#235 update drafter to work on tags & update cpu ci to target branches
  .github/workflows/cpu-ci.yml
  .github/workflows/release-drafter.yml
  tox.ini
Labels: chore, ci

#226 fil triton runtime operator created and loaded
  merlin/systems/dag/ops/compat.py
  merlin/systems/dag/ops/fil.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/runtimes/triton/ops/fil.py
  merlin/systems/dag/runtimes/triton/ops/operator.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  requirements/base.txt
  requirements/test.txt
  tests/unit/systems/dag/runtimes/triton/__init__.py
  tests/unit/systems/dag/runtimes/triton/ops/__init__.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/__init__.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_lightgbm_triton.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_sklearn_triton.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_xgboost_triton.py
  tests/unit/systems/dag/runtimes/triton/test_triton.py
  tests/unit/systems/ops/fil/test_forest.py
  tests/unit/systems/ops/fil/test_op.py
Labels: enhancement
