Repository NVIDIA-Merlin/systems, pull requests merged in 2023-06, with the labels that each got.

#353 Build docs for stable branch and make default
  .github/workflows/docs-sched-rebuild.yaml
  CONTRIBUTING.md
  README.md
  docs/source/conf.py
  docs/source/index.rst
  examples/Serving-An-Implicit-Model-With-Merlin-Systems.ipynb
  examples/Serving-An-XGboost-Model-With-Merlin-Systems.ipynb
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  requirements/docs.txt
Labels: documentation

#354 Remove the custom Workflow transform execution for serving
  merlin/systems/triton/conversions.py
  merlin/systems/workflow/base.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_ensemble.py
Labels: bug, chore

#359 Update test config to get postmerge tests running correctly
  merlin/systems/triton/conversions.py
  requirements/test-cpu.txt
  requirements/test-gpu.txt
  requirements/test.txt
  tests/integration/t4r/test_pytorch_backend.py
  tests/integration/tf/test_transformer_model.py
  tox.ini
Labels: ci

#361 Return correct dtype for offsets in TransformWorkflow Operator
  merlin/systems/triton/conversions.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_ensemble.py
Labels: chore

#363 Fix Pytorch integration test postmerge test
  merlin/systems/triton/conversions.py
  tests/integration/t4r/test_pytorch_backend.py
  tox.ini
Labels: ci

#352 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci

#365 Update handling of TensorFlow signature input names to support 2.12
  merlin/systems/dag/ops/tensorflow.py
  requirements/test-cpu.txt
Labels: bug

#366 Add feast dependency installation to `ci/test_integration.sh`
  ci/test_integration.sh
Labels: chore

#368 Update format of traceback in executor model to return string instead of list
  merlin/systems/triton/models/executor_model.py
Labels: chore

#367 Update PredictTensorflow to use low-level saved_model API
  merlin/systems/dag/ops/tensorflow.py
Labels: bug

#348 Fix reading parquet files in examples
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
Labels: bug

#349 fix readme and requirement files
  README.md
  requirements/base.txt
  requirements/gpu.txt
Labels: documentation, clean up, chore, ci

#374 Update merlin dependency versions to match 23.06 release
  requirements/base.txt
Labels: chore, skip-base-branch-check

#372 Subgraph support changes for multistage example
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/feast.py
  merlin/systems/dag/ops/implicit.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/ops/unroll_features.py
  merlin/systems/dag/ops/workflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/triton/models/executor_model.py
  tests/unit/systems/dag/runtimes/local/ops/tensorflow/test_ensemble.py
Labels: enhancement, clean up, chore
