Repository NVIDIA-Merlin/systems, pull requests merged in 2023-03, with the labels that each got.

#293 Adjust Systems to use `TensorTable` and schema shapes
  merlin/systems/dag/__init__.py
  merlin/systems/dag/dictarray.py
  merlin/systems/dag/ensemble.py
  merlin/systems/dag/ops/__init__.py
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/feast.py
  merlin/systems/dag/ops/fil.py
  merlin/systems/dag/ops/implicit.py
  merlin/systems/dag/ops/pytorch.py
  merlin/systems/dag/ops/session_filter.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/ops/workflow.py
  merlin/systems/dag/runtimes/triton/ops/fil.py
  merlin/systems/dag/runtimes/triton/ops/implicit.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/triton/__init__.py
  merlin/systems/triton/conversions.py
  merlin/systems/triton/export.py
  merlin/systems/triton/utils.py
  tests/unit/systems/dag/ops/test_ops.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_lightgbm.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_sklearn.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_xgboost.py
  tests/unit/systems/dag/runtimes/local/ops/nvtabular/test_ensemble.py
  tests/unit/systems/dag/runtimes/local/ops/tensorflow/test_ensemble.py
  tests/unit/systems/dag/runtimes/local/ops/torch/test_op.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_lightgbm_triton.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_ensemble.py
  tests/unit/systems/dag/runtimes/triton/test_triton.py
  tests/unit/systems/dag/test_column.py
  tests/unit/systems/dag/test_dict_array.py
  tests/unit/systems/dag/test_ensemble.py
  tests/unit/systems/dag/test_executors.py
  tests/unit/systems/dag/test_op_runner.py
  tests/unit/systems/ops/faiss/test_executor.py
  tests/unit/systems/ops/feast/test_op.py
  tests/unit/systems/ops/implicit/test_op.py
  tests/unit/systems/ops/tf/test_op.py
  tests/unit/systems/utils/ops.py
Labels: clean up, chore

#297 update conftest for backwards compat and new to parquet api
  tests/conftest.py
Labels: clean up, chore, ci

#294 Update default value of cpu to None in dataset fixture
  tests/conftest.py
Labels: ci

#296 Switch from `__lengths` to `__offsets` for ragged list features
  merlin/systems/dag/runtimes/triton/ops/operator.py
  merlin/systems/triton/__init__.py
  merlin/systems/triton/conversions.py
  merlin/systems/triton/export.py
  merlin/systems/triton/models/pytorch_model.py
  merlin/systems/triton/models/workflow_model.py
  merlin/systems/workflow/tensorflow.py
  tests/unit/systems/utils/tf.py
Labels: clean up, breaking, chore

#300 add detection swap for cpu based to numpy
  merlin/systems/dag/ops/tensorflow.py
Labels: chore, ci

#302 Minor fixes to post-merge test actions
  .github/workflows/postmerge-cpu.yml
  .github/workflows/postmerge-gpu.yml
Labels: chore, ci

#299 Add initial support and integration test for Merlin Models transformer models
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/ops/operator.py
  tests/integration/tf/test_transformer_model.py
Labels: enhancement

#303 Remove the extra columns validation from `WorkflowRunner`
  merlin/systems/workflow/base.py
Labels: bug

#304 Update `SoftmaxSampling` to support dynamic dtypes
  merlin/systems/dag/ops/softmax_sampling.py
  tests/unit/systems/dag/ops/test_ops.py
Labels: enhancement

#305 Remove `ensemble` specific code
  merlin/systems/dag/__init__.py
  merlin/systems/dag/node.py
  merlin/systems/dag/op_runner.py
  merlin/systems/dag/ops/faiss.py
  merlin/systems/dag/ops/fil.py
  merlin/systems/dag/ops/implicit.py
  merlin/systems/dag/ops/operator.py
  merlin/systems/dag/ops/session_filter.py
  merlin/systems/dag/ops/softmax_sampling.py
  merlin/systems/dag/ops/tensorflow.py
  merlin/systems/dag/ops/unroll_features.py
  merlin/systems/dag/ops/workflow.py
  merlin/systems/dag/runtimes/triton/ops/fil.py
  merlin/systems/dag/runtimes/triton/ops/implicit.py
  merlin/systems/dag/runtimes/triton/ops/operator.py
  merlin/systems/dag/runtimes/triton/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/triton/models/oprunner_model.py
  tests/unit/systems/dag/test_op_runner.py
  tests/unit/systems/ops/fil/test_forest.py
  tests/unit/systems/ops/implicit/test_op.py
Labels: chore

#306 Downgrade unused columns error to a warning
  merlin/systems/dag/node.py
Labels: chore

#309 Remove the Triton-specific Workflow execution code
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/workflow/__init__.py
  merlin/systems/workflow/base.py
  merlin/systems/workflow/hugectr.py
  merlin/systems/workflow/pytorch.py
  merlin/systems/workflow/tensorflow.py
  tests/unit/systems/ops/fil/test_forest.py
Labels: clean up, chore

#308 Adjust `setup_faiss` to use `METRIC_INNER_PRODUCT`
  merlin/systems/dag/ops/faiss.py
Labels: bug
