Repository NVIDIA-Merlin/systems, pull requests merged in 2023-04, with the labels that each got.

#311 remove numpy conversion for cpu based data
  merlin/systems/dag/ops/tensorflow.py
Labels: bug, clean up

#313 Revert "Remove the Triton-specific Workflow execution code (#309)"
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/workflow/__init__.py
  merlin/systems/workflow/base.py
  merlin/systems/workflow/hugectr.py
  merlin/systems/workflow/pytorch.py
  merlin/systems/workflow/tensorflow.py
  tests/unit/systems/ops/fil/test_forest.py
Labels: bug

#314 Make minor adjustments to the way `Workflow` outputs are formatted
  merlin/systems/triton/conversions.py
  merlin/systems/workflow/tensorflow.py
Labels: bug

#315 Use ragged names in workflow triton request if column is ragged
  merlin/systems/dag/runtimes/triton/ops/workflow.py
Labels: chore

#317 Convert Workflow outputs to Triton-friendly format using `TensorTable`
  merlin/systems/triton/models/workflow_model.py
  merlin/systems/workflow/tensorflow.py
Labels: bug, breaking

#318 Check offsets instead of `is_ragged` for ragged representation
  merlin/systems/triton/conversions.py
Labels: chore

#321 add AUTO kind for deployment of tritonserver and support no gpu environment
  merlin/systems/dag/runtimes/triton/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/dag/runtimes/triton/runtime.py
  merlin/systems/triton/conversions.py
  tests/conftest.py
  tests/integration/examples/test_serving_an_implicit_model_with_merlin_systems.py
  tests/unit/systems/dag/runtimes/local/ops/fil/test_xgboost.py
  tests/unit/systems/dag/runtimes/triton/ops/fil/test_xgboost_triton.py
  tests/unit/systems/ops/fil/test_ensemble.py
  tests/unit/systems/ops/fil/test_forest.py
  tests/unit/systems/ops/fil/test_op.py
Labels: enhancement, chore, ci

#319 Condense the `WorkflowRunner` sub-classes
  merlin/systems/dag/ops/workflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/triton/models/workflow_model.py
  merlin/systems/workflow/base.py
  merlin/systems/workflow/hugectr.py
  merlin/systems/workflow/pytorch.py
  merlin/systems/workflow/tensorflow.py
Labels: clean up, breaking, chore

#324 Support Ragged inputs and outputs in `TransformWorkflow` with Triton
  merlin/systems/triton/export.py
  merlin/systems/triton/models/workflow_model.py
  merlin/systems/triton/utils.py
  merlin/systems/workflow/base.py
  tests/unit/systems/dag/runtimes/triton/ops/workflow/test_ensemble.py
Labels: enhancement

#330 working padding op in systems ensemble
  tests/unit/systems/ops/padding_op.py
Labels: chore

#332 Refactor tensor representation adjustments to align with a schema
  merlin/systems/dag/runtimes/triton/ops/fil.py
  merlin/systems/dag/runtimes/triton/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/triton/conversions.py
  merlin/systems/triton/models/executor_model.py
  merlin/systems/workflow/base.py
Labels: clean up, chore

#333 Raise TritonModelException if the Triton model has an error
  merlin/systems/dag/runtimes/triton/ops/fil.py
  merlin/systems/dag/runtimes/triton/ops/pytorch.py
  merlin/systems/dag/runtimes/triton/ops/tensorflow.py
  merlin/systems/dag/runtimes/triton/ops/workflow.py
  merlin/systems/triton/models/executor_model.py
  tests/unit/systems/ops/torch/test_ensemble.py
Labels: chore

#335 Fix the code that aligns returned data with the output schema
  merlin/systems/triton/conversions.py
Labels: bug

#339 Update feast test dependency from 0.19.4 to 0.18.1
  requirements/test.txt
Labels: ci
