Repository NVIDIA-Merlin/systems, pull requests merged in 2023-05, with the labels that each got.

#342 Update tag pattern in GitHub Workflows
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/lint.yaml
  .github/workflows/postmerge-cpu.yml
  .github/workflows/postmerge-gpu.yml
  .github/workflows/release-drafter.yml
Labels: ci

#340 Add GitHub Workflow to publish conda package
  .github/workflows/cpu-ci.yml
  .github/workflows/packages.yaml
  .github/workflows/postmerge-cpu.yml
  conda/recipes/meta.yaml
Labels: chore

#341 Add workflows to check base branch and set stable branch
  .github/workflows/check-base-branch.yaml
  .github/workflows/set-stable-branch.yaml
Labels: ci

#343 Include tracebacks in errors returned from failing requests
  merlin/systems/triton/models/executor_model.py
  merlin/systems/triton/models/workflow_model.py
Labels: clean up, chore

#346 Send slack notification on failed GHA jobs
  .github/workflows/packages.yaml
  .github/workflows/postmerge-cpu.yml
  .github/workflows/postmerge-gpu.yml
Labels: chore

#347 add test requirements to postmerge gpu
  tox.ini
Labels: ci

#344 update feast op to handle feast 0.31 - latest
  merlin/systems/dag/ops/feast.py
  requirements/test-gpu.txt
  requirements/test.txt
  tests/integration/feast/test_int_feast.py
  tests/unit/systems/ops/feast/test_op.py
  tox.ini
Labels: enhancement, breaking

#351 minor syntax fixes in integration tests
  examples/Serving-Ranking-Models-With-Merlin-Systems.ipynb
  tests/integration/examples/test_serving_ranking_models_with_merlin_systems.py
  tests/integration/t4r/test_pytorch_backend.py
Labels: chore

#355 Update `test_export_merlin_models` test to run on dynamic dask cluster type
  tests/unit/systems/ops/fil/test_forest.py
Labels: ci
